### ISSUE TITLE
[Bag] ノイズが発生する

### ISSUE THREAD

**Issue by m-masaki72** [m-masaki72/SANA_8BIT_VST#9]
ノイズ発生を確認．以下条件

- PolyMode
- Waveform Memory
- ノーツに関係なくノイズが発生
- ノイズに周期性はなさそう

**Comment by COx2** [comment]
ノーツに関係ないとのことなので、バグとは関係ないと思うけど、
SImpleVoiceのlevelDiffの周辺がフォークしてもらったタイミングから若干の修正を加えていることをお知らせします。
https://github.com/COx2/JUCE_JAPAN_DEMO/blob/master/2018/SimpleSynth/Source/DSP/SimpleVoice.cpp

**Comment by m-masaki72** [comment]
把握しました．次回のリリースまでにはDiffをとって吸収しておきます．

**Comment by m-masaki72** [comment]
ノイズ発生条件その2

- モノシンセモード（numVoice = 1）
- ノーツを連続で呼び出したとき
- ノート切り替え時にプチっという感じのノイズ
- 音量の切り替えレベル差によるノイズか

**Comment by m-masaki72** [comment]
原因はAudioBufferサイズにある模様…
AudioBufferサイズが256あたりからノイズが大量に出る．
512くらいからは時々聞こえる．
1024あたりはほとんど聞こえない．
